### ISSUE TITLE
Support for NewRelic workflow

### ISSUE THREAD

**Issue by AbdelrhmanHamouda** [crossplane-contrib/provider-newrelic#37]
### What problem are you facing?
NewRelic has changed how alerting work by the introduction of [NewRelic workflows](https://docs.newrelic.com/docs/alerts-applied-intelligence/applied-intelligence/incident-workflows/incident-workflows/). Any plans to support this "and needed sub-components" soon?

### How could Crossplane help solve your problem?
Supporting the creation of a workflow and other needed sub-components

**Comment by jacob-hudson** [comment]
@smcavallo Do you have an ETA on this?

**Comment by smcavallo** [comment]
> @smcavallo Do you have an ETA on this?

Hi @AbdelrhmanHamouda and @jacob-hudson - there are no ETAs to support workflows for this proivder, but workflows are fully supported by the [upjet based provider](https://github.com/crossplane-contrib/crossplane-provider-newrelic) which can be downloaded through the marketplace:
https://marketplace.upbound.io/providers/crossplane-contrib/crossplane-provider-newrelic
That is a comprehensive implementation which allows configuration of the secrets required for notification channels and destinations as well as the associated workflows.
I would encourage you to try to use the workflow functionality in that provider.
